---
title: ""
format: # html
  typst: 
    mainfont: "C059"
    fontsize: "11pt"
    font-paths:
      - fonts
      - writing/fonts
    margin:
      x: "1.87cm"
      y: "1.87cm"
    keep-typ: true
    citeproc: true
    bibliographystyle: vancouver.csl
bibliography: ror.bib
---
# Project Description
## Objectives 
The overall aim of this project is to investigate the impact of committee group discussion on fairness in the distribution of scores and funding success of CIHR Project Grant applications. 

Although CIHR has now effectively transitioned to virtual peer review for the Project Grant scheme, this still requires considerable reviewer and panelist time, and it is unclear whether that time is needed or could possibly be allocated to additional reviews that may improve overall reliability of applications. 

## Background

Empirical evaluations of the peer review process for funding are uncommon. However, past work suggests The prior work most similar was a 2007 study of CIHR fellowship applications that estimated the impact of committee discussions [@obrecht2007] and found no evidence that discussions improved fairness. 

Considerable questions have been raised about whether existing grant panel review processes may affect funding inequalities by gender, ethnicity, or career stage. Eroshiva [@erosheva2020]

However, much of the past work on how committee dynamics and composition may affect funding success has focused more

CIHR lists 4 principles for peer review: confidentiality, absence of conflicts of interest, fairness, and transparency. 

## Methods
To estimate the impact of 

**Applicant characteristics**. 

## Expected outcomes

## Training and mentoring

Since the analysis for this project requires both an in-depth understanding of multi-level modeling as well as the ability to write computer remotely, we aim to 

## Knowledge mobilization


The Canadian Institutes for Health Research provides X% of funding for health research in Canada (cite). Determinations of priorities for research funds comes from both strategic investments as well as a process of competetive proposals. Determining which proposals are ultimately selected for funding depends chiefly on the process of review of proposals by committees of peers, charged with identifying the most promising ideas for research.

From CIHR: 
> The Project Grant program is open to applicants in all areas of health research that are aligned with the CIHR mandate. It is designed to capture ideas with the greatest potential for important advances in fundamental or applied health-related knowledge, health care, health systems, and/or health outcomes, by supporting projects of research conducted by individual researchers or groups of researchers in all areas of health. The best ideas may stem from new, incremental, innovative, and/or high-risk lines of inquiry or knowledge translation approaches.

> Project Grant applications follow a committee-based peer review process. This process involves the evaluation of applications by a group of reviewers, who have the required experience and expertise to assess the quality and potential impact of the proposed research and research related activities, within the context of the program's objectives. These reviewers are grouped into Peer Review Committees based on their expertise and the topics of applications submitted to these committees.

Although the process of peer review for funding CIHR Project Scheme applications is transparent, there remain important questions regarding whether the current procedures are optimal with respect. In practice, each application is only read and evaluated by 3 committee members assigned to each application. These reviews are detailed and the reviewers are asked to judge 

It is an open question as to how non-reviewing committee members typically assign their scores and ultimately evaluate the overall score for each application. It may be that the committee members effectively adopt the consensus score that is agreed to by the 3 reviewers after discussion. However, all committee members (including each of the reviewers) may assign their final score within a range of +/- 0.5 from the consensus score. 

## Applicant Characteristics

Several studies have shown evidence of a roughly 5% funding disadvantage for female investigators in CIHR competitions [@tamblyn2018; @witteman2019; @burns2019].

{{< pagebreak >}}

# Bibliography

::: {#refs}

:::

{{< pagebreak >}}

# Budget Justification

## Personnel costs

## Travel costs

## Other expenses

### Non-disposable equipment
Each PhD student will require a laptop for conducting relevant background research, coding policies, analyzing data, writing up manuscripts and theses (2 x \$1500). Total cost: \$3,000.

### Publication fees
We plan to make our research results widely available and estimate publishing 5 manuscripts: 1) Aim 1: construction of the database; 2) Aim 1: Changes in ECEC policy characteristics over time; 3) Aim 2: Impact of ECEC policies on cognitive outcomes; 4) Aim 2: Impact of ECEC policies on non-cognitive outcomes; 5) Aim 3: Impact of ECEC participation on child outcomes. As per the KMB plan we have specific journals targeted for these manuscripts, and we will publish these in open access format at an
estimated cost of \$2500 per manuscript. Total cost: \$12,500.

{{< pagebreak >}}

# Letters of Support
